### ISSUE TITLE
Issue with validationPath containing parameters

### ISSUE THREAD

**Issue by bazalt** [fabianwennink/IconCaptcha-Plugin-Front-End#5]
Hello,
This is my first experience with your **very interesting** solution. So to start with, thank you 👍 ; that's a great job.

I just faced an issue while setting `validationPath` to something like `validation.php?foo=bar` (I cannot operate otherwise for reasons intrinsic to a CMS).

In cause, this line in `icon-captcha.js`, which assumes that `validationPath` doesn't contain any parameter : 
https://github.com/fabianwennink/IconCaptcha-Plugin-Front-End/blob/0cb6a19cf74047e69cefb5fd44451eeba0c01f16/src/js/icon-captcha.js#L269

Do you plan to allow such behavior?
Thank you.

**Comment by fabianwennink** [comment]
Hi @bazalt! Thank you for pointing this out to me. I can for sure take this behavior/scenario into consideration. To double check I understand you correctly, the validation URL in your case should be something like this? `validation.php?foo=bar&payload=PAYLOAD`. I can fairly easily implement this by checking if the `options.general.validationPath` contain a question mark, and replace the `?payload` with a `&payload` in that case.

**Comment by bazalt** [comment]
Thanks for your positive feedback.

> the validation URL in your case should be something like this? `validation.php?foo=bar&payload=PAYLOAD`  

Exactly.

**Comment by fabianwennink** [comment]
@bazalt Can you confirm/test your issue has been resolved in this branch: `bugfix/validation-path-parameters`

**Comment by bazalt** [comment]
Hi Fabian,
This branch fixes the issue, thanks a lot 👍.

**Comment by fabianwennink** [comment]
The branch has been merged in the main branch. Version [3.1.1](https://github.com/fabianwennink/IconCaptcha-Plugin-Front-End/releases/tag/3.1.1) is now the latest release.
